require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'

target 'AddRNtest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_react_native!

  # Pods for AddRNtest

end
